### ISSUE TITLE
upload source tarball to pypi

### ISSUE THREAD

**Issue by ktdreyer** [Croydon/flask-xml-rpc-reloaded#2]
Mind publishing the source tarball to PyPI? I only see a `Flask_XML_RPC_Re-0.1.3-py2.py3-none-any.whl` available at https://pypi.org/project/Flask-XML-RPC-Re/#files

**Comment by ktdreyer** [comment]
Or maybe just cut 0.1.4 from master and release that :)

**Comment by Croydon** [comment]
Better late than never. Done! 😄

I have no active need for this module anymore. I'm still welcoming contributions, but pro-active work from myself has pretty low priority.

Cheers!

**Comment by ktdreyer** [comment]
Would you be open to having a co-maintainer? We use Flask and XML-RPC a bit at my job.

**Comment by Croydon** [comment]
> Would you be open to having a co-maintainer?

In general, yes. However, I have automated publishing via CI, so I guess pretty much everything can be done now via pull requests. If not, let me know 😄
