### ISSUE TITLE
Traceback info fault

### ISSUE THREAD

**Issue by norraxx** [Croydon/flask-xml-rpc-reloaded#9]
Mistake at 
https://github.com/Croydon/flask-xml-rpc-reloaded/blob/master/flask_xmlrpcre/xmlrepcre.py#L260

via
https://docs.python.org/3.5/library/sys.html#sys.exc_info
there is no `exec_info`

**Comment by Croydon** [comment]
Fixed via https://github.com/Croydon/flask-xml-rpc-reloaded/pull/4
